### ISSUE TITLE
getPushMessageAndChannel(msgType int ... msgType是什么参数？

### ISSUE THREAD

**Issue by SivanCola** [zituocn/getui-push#1]
`func getPushMessageAndChannel(msgType int, scheduleTime int, payload *models.CustomMessage) (pushMessage *models.PushMessage, pushChannel *models.PushChannel, setting *models.Setting, err error) {}
`
这个函数里的msgType是什么意思？我在v2文档里没有看到这个参数。

**Comment by zituocn** [comment]
对应厂商参数里的，营销和通知类消息，或 私信消息。是根据自己的业务定义的参数。

**Comment by SivanCola** [comment]
> 

在`constname.go`文件里看到了映射，不知道选取哪个可以做到通用的发送？不太想针对这么多消息类型做单独处理。

**Comment by zituocn** [comment]
最新的厂商参数有变化，已经不区别这种情况。做通用的消息发送，传1即可。

**Comment by SivanCola** [comment]
> 最新的厂商参数有变化，已经不区别这种情况。做通用的消息发送，传1即可。

`msgType`固定传1？ 我看`constname.go`里有`yuanmeng_push`这个字段出现了很多次，感觉这部分的逻辑是可以删除掉了。

**Comment by zituocn** [comment]
> > 最新的厂商参数有变化，已经不区别这种情况。做通用的消息发送，传1即可。
> 
> `msgType`固定传1？ 我看`constname.go`里有`yuanmeng_push`这个字段出现了很多次，感觉这部分的逻辑是可以删除掉了。

这部分信息，是自己在厂商后台申请的参数配置，请根据自己的实际情况做调整。

**Comment by SivanCola** [comment]
> 最新的厂商参数有变化，已经不区别这种情况。做通用的消息发送，传1即可。

那我直接为了统一发送(不区分那么多种消息类型），我直接`	msgType = 1 //默认为1` 应该就OK了？

**Comment by SivanCola** [comment]
> > 最新的厂商参数有变化，已经不区别这种情况。做通用的消息发送，传1即可。
> 
> 那我直接为了统一发送(不区分那么多种消息类型），我直接` msgType = 1 //默认为1` 应该就OK了？

`msgType = PublicChannel //默认为1` 正好`constaname.go`里有这个常量`PublicChannel = 1 //公信通道`

**Comment by zituocn** [comment]
msgType=1没有问题，android这一部分的厂商信息，请自己获取后，自行配置，否则离线消息收不了。

**Comment by SivanCola** [comment]
> 有问题，android这一部分的厂商信息，

`android这一部分的厂商信息，请自己获取后，自行配置`您指的是`平台MessageTypeChannelId`？

**Comment by zituocn** [comment]
constname.go内关于厂商的定义。
